// auto-generated by subsidy_build.py
window.SUBSIDY_DATA = {
  "generatedAt": "2026-05-21",
  "latestSnapshot": "2026-05-21",
  "historyDays": 30,
  "carriers": [
    "SKT",
    "KT",
    "LGU+"
  ],
  "subscriptionTypes": [
    "010신규",
    "MNP",
    "기변"
  ],
  "deviceVariants": [],
  "offers": [],
  "changes": [],
  "runs": [
    {
      "carrier": "KT",
      "finished_at": "2026-05-20T23:08:44.222082+00:00",
      "upserted": 0,
      "changed": 0,
      "errors": 0
    },
    {
      "carrier": "LGU+",
      "finished_at": "2026-05-20T23:09:15.340577+00:00",
      "upserted": 0,
      "changed": 0,
      "errors": 0
    },
    {
      "carrier": "SKT",
      "finished_at": "2026-05-20T23:08:04.578472+00:00",
      "upserted": 0,
      "changed": 0,
      "errors": 0
    }
  ],
  "validation": {
    "duplicates_dropped": 0,
    "invalid_dropped": 0
  }
};
